name: Photo Les
favicon: null
layout_spectrum: 0.35620948299765587
typography_spectrum: 0.880224647000432
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fe8c00'
    - '#ffc500'
    - '#ffff00'
    - '#994500'
    - '#212002'
  brandStrength: 0.5
  lightness: 0.01010397425852716
  saturation: 0.673992169322446
  rhythmicContrast: 0.6523856443818659
purpose: []
